name: flutter_projects
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  powers: ^0.1.0
  audioplayers: ^0.17.0
  cupertino_icons: ^1.0.0
  pedantic: any
  http: ^0.12.2
  redux: ^4.0.0+3
  flutter_redux: ^0.7.0
  built_value: ^7.1.0
  built_collection: ^4.3.2
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  freezed: any
  analyzer: any

flutter:

  uses-material-design: true


  assets:
    - assets/audios/




